version: '2.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  ronda:
    image: ronda
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000