version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:3.4.18-jessie
    volumes:
      - mongo-ronda:/data/db
  ronda:
    image: delmosaurio/ronda:testing
    build: .
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://mongo/ronda"
      PORT: 3000
      ADMIN_USER: "admin@ronda"
      ADMIN_PWD: "SUPERSECRET"
    volumes:
      - ronda-uploads:/var/lib/uploads
      - ./server/config/secret.js:/usr/src/app/server/config/secret.js
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongo-ronda:
    driver: local
  ronda-uploads:
    driver: local