version: '2.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-data:/data/db
  ronda:
    image: delmosaurio/ronda:testing
    build: .
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://mongo/ronda"
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - mongo